### ISSUE TITLE
Plz support Safar

### ISSUE THREAD

**Issue by abpoms** [janosaur/groovysmoothiesReal#1]
![screenshot 2015-06-05 14 21 38](https://cloud.githubusercontent.com/assets/131727/8015527/390c8c80-0b8e-11e5-9b9d-c8dda21d6a26.png)

As u can see i cant educate myself on my fav and best browser Apple MAC Safari. Plz plz plz plz sup this feature so i can make more delish smoothies.

**Comment by KelvinLu** [comment]
use a weal br0swer like chr0m3
